# version: '3'

services:

  mariadb:
    image: pm-www-mariadb
    container_name: pm-www-mariadb
    build:
      context: ./mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_TEST_NAME: ${DB_TEST_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USER_ADMIN: ${DB_USER_ADMIN}
        DB_PASSWORD_ADMIN: ${DB_PASSWORD_ADMIN}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file: .env
    restart: on-failure
    volumes:
      - db:/var/lib/mysql/:rw
    networks:
      - pm_www_net
    ports:
      - "3306:3306"
      
  nginx:
    image: pm-www-nginx
    container_name: pm-www-nginx
    build: ./nginx
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ${PM_LARAVEL}:/var/www/project-manager-laravel:rw
      - ${PM_NEXT}:/var/www/project-manager-next
      - phpmyadmin:/var/www/html/phpmyadmin
    networks:
      - pm_www_net
    restart: on-failure
    env_file: .env
    # depends_on:
    #   - web

  web:
    image: pm-www-web
    container_name: pm-www-web
    build: 
      context: ./web
    ports:
      - "9000:9000"
    volumes:
      - ${PM_LARAVEL}:/var/www/project-manager-laravel
      - ${PM_NEXT}:/var/www/project-manager-next
      - ${PM_AUTOMATES}:/automates
      - phpmyadmin:/var/www/html/phpmyadmin
    networks:
      - pm_www_net
    restart: on-failure
    env_file: .env

volumes:
  db:
    driver: local
    driver_opts:
      device: ${PM_DB}
      type: none
      o: bind
  phpmyadmin:
    driver: local
    driver_opts:
      device: ${PM_PMA}
      type: none
      o: bind

networks:
  pm_www_net:
    name: pm_www_net
