CREATE DATABASE IF NOT EXISTS `${DB_NAME}`;
CREATE DATABASE IF NOT EXISTS `${DB_TEST_NAME}`;

CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER '${DB_USER_ADMIN}'@'%' IDENTIFIED BY '${DB_PASSWORD_ADMIN}';
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER_ADMIN}'@'%';
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER}'@'%';
GRANT ALL PRIVILEGES ON `${DB_TEST_NAME}`.* TO '${DB_USER_ADMIN}'@'%';
GRANT ALL PRIVILEGES ON `${DB_TEST_NAME}`.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASSWORD}';
